config/routes.rb
Tienda::Engine.routes.draw do

  resources :product_categories
  resources :products do
    resources :variants
    collection do
      get :import
      post :import
    end
  end
  resources :orders do
    post :search, on: :collection
    member do
      post :accept
      post :reject
      post :ship
      get :despatch_note
    end
    resources :payments, only: [:create, :destroy] do
      match :refund, on: :member, via: [:get, :post]
    end
  end
  resources :stock_level_adjustments, only: [:index, :create]
  resources :delivery_services do
    resources :delivery_service_prices
  end
  resources :tax_rates
  resources :users
  resources :countries
  resources :attachments, only: :destroy
  resources :stats

  get 'settings' => 'settings#edit'
  post 'settings' => 'settings#update'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  match 'login/reset' => 'sessions#reset', via: [:get, :post]
  delete 'logout' => 'sessions#destroy'

  root to: 'dashboard#home'
end

app/models/tienda/country.rb
module Tienda

  # The Tienda::Country model stores countries which can be used for delivery & billing
  # addresses for orders.
  #
  # You can use the Tienda::CountryImporter to import a pre-defined list of countries
  # into your database. This automatically happens when you run the 'tienda:setup'
  # rake task.

  class Country < ActiveRecord::Base

    # All orders which have this country set as their billing country
    has_many :billed_orders, dependent: :restrict_with_exception, class_name: 'Tienda::Order', foreign_key: 'billing_country_id'

    # All orders which have this country set as their delivery country
    has_many :delivered_orders, dependent: :restrict_with_exception, class_name: 'Tienda::Order', foreign_key: 'delivery_country_id'

    # All countries ordered by their name asending
    scope :ordered, -> { order(:name => :asc) }

    # Validations
    validates :name, presence: true

  end
end

app/models/tienda/delivery_service.rb
module Tienda
  class DeliveryService < ActiveRecord::Base

    # Validations
    validates :name, presence: true
    validates :courier, presence: true

    # Orders which are assigned to this delivery service
    has_many :orders, dependent: :restrict_with_exception

    # Prices for the different levels of service within this delivery service
    has_many :delivery_service_prices, dependent: :destroy

    # All active delivery services
    scope :active, -> { where(active: true)}

    # Returns a tracking URL for the passed order
    #
    # @param order [Tienda::Order]
    # @return [String] the full URL for the order.
    def tracking_url_for(order)
      return nil if self.tracking_url.blank?
      tracking_url = self.tracking_url.dup
      tracking_url.gsub!("{{consignment_number}}", CGI.escape(order.consignment_number.to_s))
      tracking_url.gsub!("{{delivery_postcode}}", CGI.escape(order.delivery_postcode.to_s))
      tracking_url.gsub!("{{billing_postcode}}", CGI.escape(order.billing_postcode.to_s))
      tracking_url
    end

  end
end

app/models/tienda/delivery_service_price.rb
module Tienda
  class DeliveryServicePrice < ActiveRecord::Base

    # Set the table name
    self.table_name = 'tienda_delivery_service_prices'

    include Tienda::AssociatedCountries

    # The delivery service which this price belongs to
    belongs_to :delivery_service, :class_name => 'Tienda::DeliveryService'

    # The tax rate which should be applied
    belongs_to :tax_rate, :class_name => "Tienda::TaxRate"

    # Validations
    validates :code, :presence => true
    validates :price, :numericality => true
    validates :cost_price, :numericality => true, :allow_blank => true
    validates :min_weight, :numericality => true
    validates :max_weight, :numericality => true

    # All prices ordered by their price ascending
    scope :ordered, -> { order(:price => :asc) }

    # All prices which are suitable for the weight passed.
    #
    # @param weight [BigDecimal] the weight of the order
    scope :for_weight, -> weight { where("min_weight <= ? AND max_weight >= ?", weight, weight) }

  end
end

app/models/tienda/order.rb
module Tienda
  class Order < ActiveRecord::Base

    self.table_name = 'tienda_orders'

    # Orders can have properties
    key_value_store :properties

    # Require dependencies
    require_dependency 'tienda/order/states'
    require_dependency 'tienda/order/actions'
    require_dependency 'tienda/order/billing'
    require_dependency 'tienda/order/delivery'

    # All items which make up this order
    has_many :order_items, dependent: :destroy, class_name: 'Tienda::OrderItem'
    accepts_nested_attributes_for :order_items, allow_destroy: true, reject_if: Proc.new { |a| a['ordered_item_id'].blank? }

    # All products which are part of this order (accessed through the items)
    has_many :products, through: :order_items, class_name: 'Tienda::Product', source: :ordered_item, source_type: 'Tienda::Product'

    # Validations
    validates :token, presence: true
    with_options if: Proc.new { |o| !o.building? } do |order|
      order.validates :email_address, format: { with: /\A\b[A-Z0-9\.\_\%\-\+]+@(?:[A-Z0-9\-]+\.)+[A-Z]{2,6}\b\z/i }
      order.validates :phone_number, format: { with: /\A[\d\ \-x\(\)]{7,}\z/ }
    end

    # Set some defaults
    before_validation { self.token = SecureRandom.uuid  if self.token.blank? }

    # The order number
    #
    # @return [String] - the order number padded with at least 5 zeros
    def number
      id ? id.to_s.rjust(6, '0') : nil
    end

    # The length of time the customer spent building the order before submitting it to us.
    # The time from first item in basket to received.
    #
    # @return [Float] - the length of time
    def build_time
      return nil if self.received_at.blank?
      self.created_at - self.received_at
    end

    # The name of the customer in the format of "Company (First Last)" or if they don't have
    # company specified, just "First Last".
    #
    # @return [String]
    def customer_name
      company.blank? ? full_name : "#{company} (#{full_name})"
    end

    # The full name of the customer created by concatinting the first & last name
    #
    # @return [String]
    def full_name
      "#{first_name} #{last_name}"
    end

    # Is this order empty? (i.e. doesn't have any items associated with it)
    #
    # @return [Boolean]
    def empty?
      order_items.empty?
    end

    # Does this order have items?
    #
    # @return [Boolean]
    def has_items?
      total_items > 0
    end

    # Return the number of items in the order?
    #
    # @return [Integer]
    def total_items
      order_items.inject(0) { |t,i| t + i.quantity }
    end

    def self.ransackable_attributes(auth_object = nil)
      ['id', 'billing_postcode', 'billing_address1', 'billing_address2', 'billing_address3', 'billing_address4', 'first_name', 'last_name', 'company', 'email_address', 'phone_number', 'consignment_number', 'status', 'received_at'] + _ransackers.keys
    end

    def self.ransackable_associations(auth_object = nil)
      []
    end

  end
end

app/models/tienda/order/actions.rb
module Tienda
  class Order < ActiveRecord::Base

    extend ActiveModel::Callbacks

    # These additional callbacks allow for applications to hook into other
    # parts of the order lifecycle.
    define_model_callbacks :confirmation, :acceptance, :rejection

    # This method should be called by the base application when the user has completed their
    # first round of entering details. This will mark the order as "confirming" which means
    # the customer now just must confirm.
    #
    # @param params [Hash] a hash of order attributes
    # @return [Boolean]
    def proceed_to_confirm(params = {})
      self.status = 'confirming'
      if self.update(params)
        true
      else
        false
      end
    end

    # This method should be executed by the application when the order should be completed
    # by the customer. It will raise exceptions if anything goes wrong or return true if
    # the order has been confirmed successfully
    #
    # @return [Boolean]
    def confirm!
      no_stock_of = self.order_items.select(&:validate_stock_levels)
      unless no_stock_of.empty?
        raise Tienda::Errors::InsufficientStockToFulfil, :order => self, :out_of_stock_items => no_stock_of
      end

      run_callbacks :confirmation do
        # If we have successfully charged the card (i.e. no exception) we can go ahead and mark this
        # order as 'received' which means it can be accepted by staff.
        self.status = 'received'
        self.received_at = Time.now
        self.save!

        self.order_items.each(&:confirm!)

        # Send an email to the customer
        deliver_received_order_email
      end

      # We're all good.
      true
    end

    # Mark order as accepted
    #
    # @param user [Tienda::User] the user who carried out this action
    def accept!(user = nil)
      transaction do
        run_callbacks :acceptance do
          self.accepted_at = Time.now
          self.accepter = user if user
          self.status = 'accepted'
          self.save!
          self.order_items.each(&:accept!)
          deliver_accepted_order_email
        end
      end
    end

    # Mark order as rejected
    #
    # @param user [Tienda::User] the user who carried out the action
    def reject!(user = nil)
      transaction do
        run_callbacks :rejection do
          self.rejected_at = Time.now
          self.rejecter = user if user
          self.status = 'rejected'
          self.save!
          self.order_items.each(&:reject!)
          deliver_rejected_order_email
        end
      end
    end

    def deliver_accepted_order_email
      Tienda::OrderMailer.accepted(self).deliver_now
    end

    def deliver_rejected_order_email
      Tienda::OrderMailer.rejected(self).deliver_now
    end

    def deliver_received_order_email
      Tienda::OrderMailer.received(self).deliver_now
    end

  end
end

app/models/tienda/order/billing.rb
module Tienda
  class Order < ActiveRecord::Base

    # The country which this order should be billed to
    #
    # @return [Tienda::Country]
    belongs_to :billing_country, :class_name => 'Tienda::Country', :foreign_key => 'billing_country_id'

    # Payments which have been stored for the order
    has_many :payments, :dependent => :destroy, :class_name => 'Tienda::Payment'

    # Validations
    with_options :if => Proc.new { |o| !o.building? } do |order|
      order.validates :first_name, :presence => true
      order.validates :last_name, :presence => true
      order.validates :billing_address1, :presence => true
      order.validates :billing_address3, :presence => true
      order.validates :billing_address4, :presence => true
      order.validates :billing_postcode, :presence => true
      order.validates :billing_country, :presence => true
    end

    # The name for billing purposes
    #
    # @return [String]
    def billing_name
      company.blank? ? full_name : "#{full_name} (#{company})"
    end

    # The total cost of the order
    #
    # @return [BigDecimal]
    def total_cost
      self.delivery_cost_price +
      order_items.inject(BigDecimal(0)) { |t, i| t + i.total_cost }
    end

    # Return the price for the order
    #
    # @return [BigDecimal]
    def profit
      total_before_tax - total_cost
    end

    # The total price of all items in the basket excluding delivery
    #
    # @return [BigDecimal]
    def items_sub_total
      order_items.inject(BigDecimal(0)) { |t, i| t + i.sub_total }
    end

    # The total price of the order before tax
    #
    # @return [BigDecimal]
    def total_before_tax
      self.delivery_price + self.items_sub_total
    end

    # The total amount of tax due on this order
    #
    # @return [BigDecimal]
    def tax
      self.delivery_tax_amount +
      order_items.inject(BigDecimal(0)) { |t, i| t + i.tax_amount }
    end

    # The total of the order including tax
    #
    # @return [BigDecimal]
    def total
      self.delivery_price +
      self.delivery_tax_amount +
      order_items.inject(BigDecimal(0)) { |t, i| t + i.total }
    end

    # The total amount due on the order
    #
    # @return [BigDecimal]
    def balance
      @balance ||= total - amount_paid
    end

    # Is there a payment still outstanding on this order?
    #
    # @return [Boolean]
    def payment_outstanding?
      balance > BigDecimal(0)
    end

    # Has this order been paid in full?
    #
    # @return [Boolean]
    def paid_in_full?
      !payment_outstanding?
    end

    # Is the order invoiced?
    #
    # @return [Boolean]
    def invoiced?
      !invoice_number.blank?
    end

  end
end

app/models/tienda/order/states.rb
module Tienda
  class Order < ActiveRecord::Base

    # An array of all the available statuses for an order
    STATUSES = ['building', 'confirming', 'received', 'accepted', 'rejected', 'shipped']

    # The Tienda::User who accepted the order
    #
    # @return [Tienda::User]
    belongs_to :accepter, :class_name => 'Tienda::User', :foreign_key => 'accepted_by'

    # The Tienda::User who rejected the order
    #
    # @return [Tienda::User]
    belongs_to :rejecter, :class_name => 'Tienda::User', :foreign_key => 'rejected_by'

    # Validations
    validates :status, :inclusion => {:in => STATUSES}

    # Set the status to building if we don't have a status
    after_initialize  { self.status = STATUSES.first if self.status.blank? }

    # All orders which have been received
    scope :received, -> {where("received_at is not null")}

    # All orders which are currently pending acceptance/rejection
    scope :pending, -> { where(:status => 'received') }

    # All ordered ordered by their ID desending
    scope :ordered, -> { order(:id => :desc)}

    # All accepted Orders
    scope :accepted, -> { where.not(accepted_at: nil) }

    # Is this order still being built by the user?
    #
    # @return [Boolean]
    def building?
      self.status == 'building'
    end

    # Is this order in the user confirmation step?
    #
    # @return [Boolean]
    def confirming?
      self.status == 'confirming'
    end

    # Has this order been rejected?
    #
    # @return [Boolean]
    def rejected?
      !!self.rejected_at
    end

    # Has this order been accepted?
    #
    # @return [Boolean]
    def accepted?
      !!self.accepted_at
    end

    # Has the order been received?
    #
    # @return [Boolean]
    def received?
      !!self.received_at?
    end


  end
end

app/models/tienda/payment.rb
module Tienda
  class Payment < ActiveRecord::Base

    # The associated order
    #
    # @return [Tienda::Order]
    belongs_to :order, :class_name => 'Tienda::Order'

    # An associated payment (only applies to refunds)
    #
    # @return [Tienda::Payment]
    belongs_to :parent, :class_name => "Tienda::Payment", :foreign_key => "parent_payment_id"

    # Validatiosn
    validates :amount, :numericality => true
    validates :reference, :presence => true
    validates :method, :presence => true

    # Payments can have associated properties
    key_value_store :properties

    # Callbacks
    after_create :cache_amount_paid
    after_destroy :cache_amount_paid
    before_destroy { self.parent.update_attribute(:amount_refunded, self.parent.amount_refunded + amount) if self.parent }

    # Is this payment a refund?
    #
    # @return [Boolean]
    def refund?
      self.amount < BigDecimal(0)
    end

    # Has this payment had any refunds taken from it?
    #
    # @return [Boolean]
    def refunded?
      self.amount_refunded > BigDecimal(0)
    end

    # How much of the payment can be refunded
    #
    # @return [BigDecimal]
    def refundable_amount
      refundable? ? (self.amount - self.amount_refunded) : BigDecimal(0)
    end

    # Process a refund from this payment.
    #
    # @param amount [String] the amount which should be refunded
    # @return [Boolean]
    def refund!(amount)
      amount = BigDecimal(amount)
      if refundable_amount >= amount
        transaction do
          self.class.create(:parent => self, :order_id => self.order_id, :amount => 0-amount, :method => self.method, :reference => reference)
          self.update_attribute(:amount_refunded, self.amount_refunded + amount)
          true
        end
      else
        raise Tienda::Errors::RefundFailed, :message => I18n.t('.refund_failed', refundable_amount: refundable_amount)
      end
    end

    # Return a transaction URL for viewing further information about this
    # payment.
    #
    # @return [String]
    def transaction_url
      nil
    end

    private

    def cache_amount_paid
      self.order.update_attribute(:amount_paid, self.order.payments.sum(:amount))
    end

  end
end

app/models/tienda/product/product_attributes.rb
module Tienda
  class Product < ActiveRecord::Base

    # Product attributes for this product
    has_many :product_attributes, -> { order(:position) }, :class_name => 'Tienda::ProductAttribute'

    # Used for setting an array of product attributes which will be updated. Usually
    # received from a web browser.
    attr_accessor :product_attributes_array

    # After saving automatically try to update the product attributes based on the
    # the contents of the product_attributes_array array.
    after_save do
      if product_attributes_array.is_a?(Array)
        self.product_attributes.update_from_array(product_attributes_array)
      end
    end

  end
end

app/models/tienda/product_image.rb
module Tienda
  class ProductImage < ActiveRecord::Base
    # Relationships
    belongs_to :product

    # Mount Uploaders
    mount_uploader :image, ProductImageUploader
  end
end

app/views/tienda/orders/_form.html.haml
= field_set_tag t('tienda.orders.billing_address') do
  .row
    .col-md-4
      .form-group
        = f.label :first_name, t('tienda.orders.first_name')
        = f.text_field :first_name, class: 'focus form-control'
    .col-md-4
      .form-group
        = f.label :last_name, t('tienda.orders.last_name')
        = f.text_field :last_name, class: 'form-control'
    .col-md-4
      .form-group
        = f.label :company, t('tienda.orders.company')
        = f.text_field :company, class: 'form-control'
  .row
    .col-md-12
      &nbsp;
  .row
    .col-md-12
      .form-group
        = f.label :billing_address1, t('tienda.orders.address')
        = f.text_field :billing_address1, class: 'form-control'
        = f.text_field :billing_address2, class: 'form-control'
        = f.text_field :billing_address3, class: 'form-control'
        = f.text_field :billing_address4, class: 'form-control'
  .row
    .col-md-12
      &nbsp;
  .row
    .col-md-6
      .form-group
        = f.label :billing_postcode, t('tienda.orders.post_code')
        = f.text_field :billing_postcode, class: 'form-control'
    .col-md-6
      .form-group
        = f.label :billing_country_id, t('tienda.orders.country')
        = f.collection_select :billing_country_id, Tienda::Country.ordered, :id, :name, {include_blank: true}, {class: 'form-control', data: {placeholder: t('tienda.orders.select_country')}}
  .row
    .col-md-12
      &nbsp;
  .row
    .col-md-4
      .form-group
        = f.label :email_address, t('tienda.orders.email_address')
        = f.text_field :email_address, class: 'form-control'
    .col-md-4
      .form-group
        = f.label :phone_number, t('tienda.orders.phone_number')
        = f.text_field :phone_number, class: 'form-control'
    .col-md-4
      .form-group
        = f.label :separate_delivery_address, t('tienda.orders.separate_delivery_address')
        .checkbox
          %label
            = f.check_box :separate_delivery_address
            = t('tienda.orders.use_separate_delivery_address?')

= field_set_tag t('tienda.orders.delivery_address'), class: 'delivery' do
  .row
    .col-md-12
      .form-group
        = f.label :delivery_name, t('tienda.orders.delivery_name')
        = f.text_field :delivery_name, class: 'form-control'
  .row
    .col-md-12
      .form-group
        = f.label :delivery_address1, t('tienda.orders.address')
        = f.text_field :delivery_address1, class: 'form-control'
        = f.text_field :delivery_address2, class: 'form-control'
        = f.text_field :delivery_address3, class: 'form-control'
        = f.text_field :delivery_address4, class: 'form-control'
  .row
    .col-md-6
      .form-group
        = f.label :delivery_postcode, t('tienda.orders.post_code')
        = f.text_field :delivery_postcode, class: 'form-control'
    .col-md-6
      .form-group
        = f.label :delivery_country_id, t('tienda.orders.country')
        = f.collection_select :delivery_country_id, Tienda::Country.ordered, :id, :name, {include_blank: true}, {class: 'form-control', data: {placeholder: t('tienda.orders.select_country')}}

app/views/tienda/orders/_order_details.html.haml
.panel.panel-default
  .panel-heading
    Order Details
  .panel-body
    .col-md-6
      %dl
        %dt= t('tienda.orders.name')
        %dd= @order.full_name
        %dt= t('tienda.orders.company')
        %dd= @order.company.blank? ? '-' : @order.company
        %dt
          - if @order.separate_delivery_address?
            = t('tienda.orders.billing_address')
          - else
            = t('tienda.orders.billing_delivery_address')

        %dd= @order.billing_address1
        %dd= @order.billing_address2
        %dd= @order.billing_address3
        %dd= @order.billing_address4
        %dd= @order.billing_postcode
        %dd= @order.billing_country.try(:name)
        - if @order.separate_delivery_address?
          %dt= t('tienda.orders.delivery_address')
          %dd= @order.delivery_name
          %dd= @order.delivery_address1
          %dd= @order.delivery_address2
          %dd= @order.delivery_address3
          %dd= @order.delivery_address4
          %dd= @order.delivery_postcode
          %dd= @order.delivery_country.try(:name)
    .col-md-6
      %dl
        %dt= t('tienda.orders.email_address')
        %dd= mail_to @order.email_address
        %dt= t('tienda.orders.telephone')
        %dd= @order.phone_number
        %dt= t('tienda.orders.weight')
        %dd= number_to_weight @order.total_weight
        - if @order.received?
          %dt= t('tienda.orders.build_time')
          %dd= distance_of_time_in_words(@order.created_at, @order.received_at)
        - if @order.invoiced?
          %dt= t('tienda.orders.invoice_number')
          %dd= @order.invoice_number
        %dt= t('tienda.orders.order_balance')
        %dd= boolean_tag @order.paid_in_full?, nil, true_text: number_to_currency(@order.balance), false_text: number_to_currency(@order.balance)
      - if @order.accepted? && !@order.shipped?
        = form_tag [:ship, @order] do
          .form-group
            = label_tag 'consignment_number', t('tienda.orders.consignment_number')
            = text_field_tag 'consignment_number', '', class: 'form-control'
          .form-group
            = submit_tag t('tienda.orders.mark_as_shipped') , class: 'btn btn-primary btn-sm'

      - unless @order.accepted? || @order.rejected?
        %dl.form
          %dd
            = link_to t('tienda.orders.accept'), [:accept, @order], method: :post, class: 'btn btn-primary'
            = link_to t('tienda.orders.reject'), [:reject, @order], method: :post, class: 'btn btn-danger'

app/views/tienda/orders/_order_items.html.haml
.panel.panel-default
  .panel-heading
    = t('tienda.orders.order_items')
  .panel-body
    %table.table.table-hover
      %thead
        %tr
          %th.qty= t('tienda.orders.qty')
          %th= t('tienda.orders.item')
          %th= t('tienda.orders.sku')
          %th.money= t('tienda.orders.cost')
          %th.money= t('tienda.orders.price')
          %th.money= Tienda.settings.tax_name
          %th.money= t('tienda.orders.sub_total')
      %tbody
        - for item in @order.order_items
          %tr
            %td.qty= item.quantity
            %td.product= item.ordered_item.full_name
            %td.sku= item.ordered_item.sku
            %td.money= number_to_currency item.total_cost
            %td.money= number_to_currency item.sub_total
            %td.money= number_to_currency item.tax_amount
            %td.money= number_to_currency item.total
        - if @order.delivery_service
          %td.qty
          %td.product= link_to @order.delivery_service.name, [:edit, @order.delivery_service]
          %td.sku
          %td.money= number_to_currency @order.delivery_cost_price
          %td.money= number_to_currency @order.delivery_price
          %td.money= number_to_currency @order.delivery_tax_amount
          %td.money= number_to_currency @order.delivery_price + @order.delivery_tax_amount
      %tfoot
        %tr
          %td.qty= @order.total_items
          %td{:colspan => 2}
          %td.money= number_to_currency @order.total_cost
          %td.money= number_to_currency @order.total_before_tax
          %td.money= number_to_currency @order.tax
          %td.money= number_to_currency @order.total

app/views/tienda/orders/_payments_form.html.haml
= form_for [@order, Tienda::Payment.new(:amount => @order.balance)] do |f|
  .col-md-3
    .form-group
      = f.label :method, t('tienda.orders.method')
      = f.text_field :method, class: 'form-control'
  .col-md-3
    .form-group
      = f.label :reference, t('tienda.orders.reference')
      = f.text_field :reference, class: 'form-control'
  .col-md-3
    .form-group
      = f.label :amount, t('tienda.orders.amount')
      .form-group.input-group
        %span.input-group-addon= Tienda.settings.currency_unit.html_safe
        = f.text_field :amount, class: 'form-control'
  .col-md-3
    .form-group
      %br
      = f.submit t('tienda.orders.add_payment') , class: 'btn btn-primary'

app/views/tienda/orders/_payments_table.html.haml
- unless @payments.empty?
  .table
    %table.table.table-hover
      %thead
        %tr
          %th= t('tienda.orders.id')
          %th= t('tienda.orders.type')
          %th= t('tienda.orders.method')
          %th= t('tienda.orders.reference')
          %th= t('tienda.orders.amount')
          %th= t('tienda.orders.refunded?')
          %th
      %tbody
        - for payment in @payments
          %tr
            %td= payment.id
            %td
              = payment.refund? ? t('tienda.orders.refund') : t('tienda.orders.payment')
              %span.float-right= boolean_tag payment.confirmed?
            %td= payment.method
            %td= link_to_if payment.transaction_url, payment.reference, payment.transaction_url

            - if payment.refund?
              %td{:colspan => 2}
                %b= number_to_currency payment.amount
                - if payment.parent_payment_id
                  #{t('tienda.orders.from_payment')} ##{payment.parent_payment_id}
            - else
              %td= number_to_currency payment.amount
              %td= boolean_tag payment.refunded?, nil, true_text: number_to_currency(payment.amount_refunded)
            %td.refund
              - if payment.refundable?
                = link_to t('tienda.orders.refund'), [:refund, @order, payment], class: 'btn btn-danger btn-sm', rel: 'dialog'
              - else
                = link_to t('tienda.delete'), [@order, payment], class: 'btn btn-danger btn-sm', data: {confirm: t('tienda.orders.payment_remove_confirmation') }, method: :delete
- else
  .alert.alert-warning
    = t('tienda.orders.no_payments')

app/views/tienda/orders/_search_form.html.haml
.panel.panel-default.search-orders.hide{style: action_name == 'search' ? 'display:block' : ''}
  .panel-heading
    Search orders
  .panel-body
    = search_form_for @query, url: search_orders_path, html: { method: :post } do |f|
      .row
        .col-md-6
          .form-group
            = f.label :id_eq, t('tienda.orders.order_number')
            = f.text_field :id_eq, class: 'form-control'
          .form-group
            = f.label :first_name_or_last_name_or_company_cont, t('tienda.orders.customer')
            = f.text_field :first_name_or_last_name_or_company_cont, class: 'form-control'
          .form-group
            = f.label :address1_or_address2_or_address3_or_address4_or_postcode_cont, t('tienda.orders.billing_address')
            = f.text_field :billing_address1_or_billing_address2_or_billing_address3_or_billing_address4_or_billing_postcode_cont, class: 'form-control'
          .form-group
            = f.label :consignment_number_cont, t('tienda.orders.consignment_number')
            = f.text_field :consignment_number_cont, class: 'form-control'
          .row
            .col-md-12
              = f.label :received_at_eq, t('tienda.orders.received_between')
            .col-md-5
              = f.text_field :received_at_gteq, class: 'form-control col-md-5'
            .col-md-1
              %p.form-control-static
                &rarr;
            .col-md-6
              = f.text_field :received_at_lteq, class: 'form-control col-md-5'
        .col-md-6
          .form-group
            = f.label :email_address_cont, t('tienda.orders.email_address')
            = f.text_field :email_address_cont, class: 'form-control'
          .form-group
            = f.label :phone_number_cont, t('tienda.orders.phone_number')
            = f.text_field :phone_number_cont, class: 'form-control'
          .form-group
            = f.label :status_eq, t('tienda.orders.status')
            = f.select :status_eq, [nil] + Tienda::Order::STATUSES.map { |s| [t("tienda.orders.statuses.#{s}"), s]}, {}, class: 'form-control'
          = f.submit  t('tienda.orders.search'), class: 'btn btn-primary'